name: gloalo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_keyboard_visibility: ^6.0.0
  introduction_screen: ^3.0.2
  markdown_widget: ^2.3.2+6
  url_launcher: ^6.3.1
  dropdown_search: ^6.0.2
  carousel_slider: ^5.0.0
  animated_splash_screen: ^1.3.0
  lottie: ^3.2.0
  flutter_animated_splash: ^0.0.10
  device_info_plus: ^11.3.0
  flutter_esim: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  url_launcher: ^6.1.11
  shared_preferences: ^2.0.17
  http:
  flutter_launcher_icons: 
flutter_icons: 
  image_path: "assets/visuals/app_icon.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/google.png
    - assets/privacy_policy.md
    - assets/visuals/no_card.png
    - assets/visuals/Group-1.png
    - assets/visuals/Group-2.png
    - assets/visuals/Group.png
    - assets/visuals/notLoggedInHome.png
    - assets/visuals/slides/germany_slide.png
    - assets/visuals/slides/italy_slide.png
    - assets/animation/animation.json
    - assets/flags/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-VariableFont_wght.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf


